version: '3.1'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREcvXDs9Gk89Ef
    volumes:
      - ./data:/var/lib/postgresql/data